name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:24.0

    steps:
    - uses: actions/checkout@v2
    - name: Install apt packages
      run:  sudo apt update && sudo apt install -yy grep binutils-multiarch
    - name: Compile
      run:  make
    - name: Run tests
      run:  make test
